import type { Config } from "tailwindcss";

export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        bg: "var(--bg)",
        background: "var(--bg)",
        surface: "var(--surface)",
        "surface-muted": "var(--surface-muted)",
        text: "var(--text)",
        muted: "var(--muted)",
        primary: "var(--primary)",
        "primary-text": "var(--primary-text)",
        primaryText: "var(--primary-text)",
        calm: "var(--calm)",
        accent: "var(--accent)",
        "accent-light": "var(--accent-light)",
        lavender: "var(--lavender)",
        border: "var(--border)",
        info: "var(--info)",
        success: "var(--success)",
        warn: "var(--warn)",
        warning: "var(--warn)",
        danger: "var(--danger)",
        "text-primary": "var(--color-text-primary)",
        "text-secondary": "var(--color-text-secondary)",
        "text-muted": "var(--color-text-muted)",
        "border-default": "var(--color-border-default)",
        "border-strong": "var(--color-border-strong)",
        "chart-memory": "var(--color-chart-memory)",
        "chart-attention": "var(--color-chart-attention)",
        "chart-recall": "var(--color-chart-recall)",
        "chart-pattern": "var(--color-chart-pattern)",
      },
      borderRadius: {
        sm: "var(--radius-small)",
        md: "var(--radius-medium)",
        lg: "var(--radius-large)",
        xl: "var(--radius-extra-large)",
        card: "var(--radius-card)",
        control: "var(--radius-control)",
        pill: "999px",
      },
      boxShadow: {
        card: "var(--shadow-card)",
        lift: "var(--shadow-lift)",
        soft: "var(--shadow-soft)",
        interactive: "var(--shadow-interactive)",
      },
      fontFamily: {
        display: ["var(--font-display)"],
        body: ["var(--font-body)"],
      },
      transitionDuration: {
        fast: "var(--motion-fast)",
        normal: "var(--motion-normal)",
      },
    },
  },
  plugins: [],
} satisfies Config;
